### ISSUE TITLE
6.1 to 6.1 migrate  not working

### ISSUE THREAD

**Issue by gudge25** [djamps/migrate-vm#13]
new  VM  Storage not mapping 
(i think it maybe because  VM itself  was created from snapshot or template )

![image](https://user-images.githubusercontent.com/2346208/44058733-cd8ba692-9f57-11e8-826c-290286f53a8a.png)
Please  help

**Comment by gudge25** [comment]
![image](https://user-images.githubusercontent.com/2346208/44060498-855123b0-9f5d-11e8-9d6a-e8088c0d07c5.png)
From Server IMAGE

**Comment by gudge25** [comment]
Update 
(created from snapshot or template=doesn't matter) 
tested  with another VM ---same prob

**Comment by steaksauce-** [comment]
Is there a default SR set on the destination?

**Comment by gudge25** [comment]
@steaksauce-   I sound solution   --- ISO was mounted during migrate --- so  unmount iso  and then start a migration --YAHOO!!! :)
