### ISSUE TITLE
Could Not find VM 

### ISSUE THREAD

**Issue by tmc81** [djamps/migrate-vm#16]
Dear Randy,

I was able to run your wonderful script on Xenserver 7.2 after installing several perl modules, but I get this error:
Connecting to source host
Connecting to destination host and Starting transfer
Could not find VM OSTicket at lib/Xen/API.pm line 123.

Tried with command line parameters, VM name and UUID, same results. VM is halted, no pool or shared storage.

Any suggestions?

**Comment by steaksauce-** [comment]
Out of curiosity, is the VM located in the Default SR on the source?

If not. try to set the SR that the VM is located in a the Default SR. When moving the VM, the script looks inside the Default SR and will move the VM to the Default SR on the destination.

**Comment by tmc81** [comment]
Yes, both servers are using default SR.

**Comment by tmc81** [comment]
Although... I think I may be wrong. I remembered adding more storage on that server... I'll let you know. Thanks

**Comment by tmc81** [comment]
Indeed. VM is located on Local Storage marked as default.

**Comment by djamps** [comment]
Check the output of xe vm-list to confirm what you're seeing in Xencenter?

**Comment by tmc81** [comment]
Here's the output:

uuid ( RO)           : 3a7202a7-c396-4e41-b726-0d14b4dd3e88
     name-label ( RW): Control domain on host: xs-gp01
    power-state ( RO): running


uuid ( RO)           : 4ad66499-0a07-f157-0561-ff61c3d8b97b
     name-label ( RW): SymServer
    power-state ( RO): halted


uuid ( RO)           : bff84a15-bc1b-9653-0e95-f6fcccdf4d55
     name-label ( RW): OSTicket
    power-state ( RO): running


uuid ( RO)           : 48911124-1141-ab01-986a-a81b68b8d6bd
     name-label ( RW): PrintServer
    power-state ( RO): running

Tried this command:
[root@xs-gp01 migrate-vm-master]# ./migratevm.pl -sh localhost -su root -sp gpaz100.3 -sv SymServer -dh 192.168.200.110 -du root -dp **********
migratevm 1.2.0 started
Destination SR on 192.168.200.110 (blank for default):
Connecting to source host
Connecting to destination host and Starting transfer
Could not find VM SymServer at lib/Xen/API.pm line 123.

**Comment by djamps** [comment]
Curious if the comments here are filtering out quotes or if you're running different code... mine returns the following on invalid vm's:

Could not find VM 'asd'

Notice the quotes around ASD.   Are you running the latest code?

Have you tried running the docker build script on a CentOS 7 based machine?   That's what I'm using to create standlone, portable binary.   I haven't tried to run the perl code directly on a Xenserver box for years.   I suspect some perl module conflict may be at play here.

**Comment by tmc81** [comment]
It was the script found here. I didn't have a CentOS box running, so I've tried doing it directly on the Xenserver console (hence the missing dependencies I mentioned). I guess I'll start deploying a CentOS VM. I think thats the best approach by now.

**Comment by tmc81** [comment]
BTW thanks for your fast replies and your great script. I'll let you know if the docker script worked (I'm confident it will)
