### ISSUE TITLE
support in xenserver 8.2

### ISSUE THREAD

**Issue by mipstream** [djamps/migrate-vm#17]
Hello guys.
very appreciate this project. I'm using it for several years already.

anyway I've jumped to xenserver 8.2 and hit an issue with migratevm
Can you help me to resolve it?

" ./migratevm.pl 
Can't locate RPC/XML.pm in @INC (@INC contains: ./lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at lib/Xen/API.pm line 3.
BEGIN failed--compilation aborted at lib/Xen/API.pm line 3.
Compilation failed in require at ./migratevm.pl line 5.
BEGIN failed--compilation aborted at ./migratevm.pl line 5."

**Comment by djamps** [comment]
Did you try to build the stand alone binary on centos7?  There is a docker script to do it.  You cannot run the .pl file directly on a xen server.
