### ISSUE TITLE
Migrate from xenserver 6.2 to xcp-ng

### ISSUE THREAD

**Issue by anndix** [djamps/migrate-vm#18]
Hi,

I have used your tool several times to move vm between 2 xenserver machines without any problems in the past. Lately i installed xcp-ng on a new machine to migrate away from xenserver.

Can this work for migrating vm from xenserver 6.2 to xcp-ng ? I have tried a few methods, including vm-export and vm-import yet the vm doesn't boot up on xcp-ng.

The vm is on PV in xenserver, and conversion to HVM before / after move to xcp-ng doesn't help either. The vm console just complains about missing boot disk.

`XenServer release 6.2.0-70446c (xenenterprise)`
`XCP-ng release 8.2.0 (xenenterprise)`

Any help would be highly appreciated.

Thanks

**Comment by gn-ro** [comment]
Hi, 

I think your problem is related to Citrix drivers from inside the vm. Uninstall them and try again.

**Comment by anndix** [comment]
Thanks for your reply. I have tried to remove citrix drivers and tried, still doesn't work. The transfered VM is non bootable..

Thanks

**Comment by anndix** [comment]
I re-downloaded the compiled version from website, removed the guest utils and 1 vm got migrated successfully. 

However for rest issue persists.

I have found something common in the rest vms. All of them have xvda as single disk which is bootable in pv mode. Could it be on the new system it's unable to find the bootable disk ? How to mark disk as bootable when there is no partition table on the main disk. 

Thanks

**Comment by gn-ro** [comment]
The virtual disk MUST be marked as boot-able to be able to boot from it, at least in BIOS mode and I'm pretty sure your vm's are in BIOS mode.

You can try to migrate first to a older version of XCP-ng (7.0 first?) then to a newer one or latest. I don't remember all changes, but this may help.

**Comment by anndix** [comment]
Thanks for the reply. The disks have no partition, just plain xvda. Would it work ? 

Will try shortly.

Thanks

**Comment by anndix** [comment]
This is what i see when i try to boot. The process goes so fast that its impossible to go to bios or boot menu.

<img width="744" alt="Screenshot 2022-09-15 at 9 39 57 PM" src="https://user-images.githubusercontent.com/50706506/190454132-c6450e17-bc6f-4763-9b7b-fb361b22d94d.png">

Thanks

**Comment by gn-ro** [comment]
I see you have 2 drives: 10Gb and 50Gb. Which one is the boot drive? What operating system? Do you use XOA or XenCenter? If is XOA you can alter the boot order in the advanced tab of the vm. If it's XenCenter or XCPng Center you can alter the boot order from Properties then boot order.

**Comment by anndix** [comment]
Hi,

10GB is the bootable drive. OS is Centos 6.10.

I have tried to use XenCenter and XOA both. Using the advanced menu I have the hdd selected as bootable, however the error i shared is what come shows up on the screen.

Thanks

**Comment by gn-ro** [comment]
That means you should have grub bootloader. I can't understand why the transfer is not working but you can try other method too: export the vm to local xen 6.2 server as a xva, then copy this to XCP then import the xva.
If this does not work, then it's probably the problem below:

I think it's possible that grub is really not installed correctly on the vm. From what I know, xen 6.2 uses some scripts to load the linux vm from it's drive, bypassing the BIOS way. When you transfer the vm on XCP, XCP tries to boot like a normal computer, but the drive is not boot-able or grub is not found.

**Comment by anndix** [comment]
> That means you should have grub bootloader. I can't understand why the transfer is not working but you can try other method too: export the vm to local xen 6.2 server as a xva, then copy this to XCP then import the xva. If this does not work, then it's probably the problem below:
> 
> I think it's possible that grub is really not installed correctly on the vm. From what I know, xen 6.2 uses some scripts to load the linux vm from it's drive, bypassing the BIOS way. When you transfer the vm on XCP, XCP tries to boot like a normal computer, but the drive is not boot-able or grub is not found.

Thanks for your reply. What you said, makes sense. Is there a way to install grub ? I tried grub-install, and it gave error.

`grub-install /dev/xvda 
Probing devices to guess BIOS drives. This may take a long time.
No suitable drive was found in the generated device map.`

Thanks
