### ISSUE TITLE
Unable to migrate from 6.5 to 6.2

### ISSUE THREAD

**Issue by warden** [djamps/migrate-vm#4]
Trying to migrate from XEN 6.2 to 6.5 ends with:
(executing on 6.5)

```
Can't use an undefined value as an ARRAY reference at /tmp/par-root/cache-8fcf61b50a66b7ac0e88ea6c3bfc3ae255e6247a/inc/lib/Xen/API.pm line 305.
```

**Comment by warden** [comment]
By the way, executing from downloaded version 1.0.2  displays:
migratevm 1.0.1 started.

**Comment by djamps** [comment]
In my experience that message indicates and authentication or connection error.   I haven't found a graceful way to display certain errors but I'm pretty certain on this one.   Bear in mind, it connects over port 80 so make sure it's open on Dom0 firewall.   I'll fix the versioning issue as well :)

**Comment by warden** [comment]
That's interesting. I'm pretty sure I am giving the right credentials :) Are special characters like !#$@* supported in the password? I can imagine that could break things...

**Comment by djamps** [comment]
Shouldn't matter.   But Maybe... could you reset to a simpler password to test?   Also make sure you can connect via XE and run basic commands on the command line to both machines.
