### ISSUE TITLE
Unable to move VM from 6.5 to 6.5 within same pool

### ISSUE THREAD

**Issue by fetzerms** [djamps/migrate-vm#5]
I am trying to move a VM from a pool slave to the pool master. Both only using local storage,
using the binary release from http://djlab.com/stuff/migratevm-1.0.2.tar.gz . It does not matter where I execute the command, the error is the same.

I am getting the following error:

Can't use an undefined value as an ARRAY reference at /tmp/par-root/cache-1ef67fd02ac4e48d37c75f30223c07ddbb73f4d2/inc/lib/Xen/API.pm line 108.

How can I help in debugging this error? Maybe this is related to #4

Note: Transfering to the 6.5 slave from a 6.2 Machine worked great without any problems.

**Comment by djamps** [comment]
This usually means you forgot to stop the VM before migrating it.   Also, AFAIK -- since 6.2 you can move VM's between hosts in the pool even with local storage.   In fact, there's an XE command to do it between pools.

**Comment by fetzerms** [comment]
Thank you for your fast reply. The VM is/was powered off. The error happens on any (powered off) VM in any direction.

Moving VMs via XenCenter works fine, but afaik requires some additional available local storage on the source XS, which i currently don't have. But I will look into it again, and see how it may solve my issue.

**Comment by SchoolBusDriver** [comment]
I am seeing the same issue. 

I have used your great tool many times before. With latest XenServer 6.5 Hotfixes when a VM is powered down your script no longer works.

If there is any additional I can provide, please let me know.

**Comment by fetzerms** [comment]
I do not have any primary SR set on both servers aswell. The servers are in a pool and cannot have their local SR as the primary one. Maybe this could be fixed with passing the source-sr as a parameter?
