### ISSUE TITLE
Transfer rates?

### ISSUE THREAD

**Issue by ghost** [djamps/migrate-vm#8]
What transfer rates do you typically see in your normal usage? We like this method but notice it maxes out around 50 megabytes/second, far below the surrounding hardware capabilities.

We suspect its a processing issue either in the script or just Xen itself doing all the work.  Do you know if the script can be adjusted to increase that at all?

**Comment by djamps** [comment]
A change was made recently to speed up transfers.   To go even faster, parallel read/write threads will be needed and that is beyond my capability at the moment.   Closing the ticket for now.
